name: CI
on: workflow_dispatch

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create dir
        run: |
          mkdir TestArtifact

      # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Install Newman globally, the reporter for Slack, and install the HTML extra reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-htmlextra

      # Run the POSTMAN Collection
      - name: Run Tests
        run: |
          newman run ".postman/postman/collections/EDA.json" -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html

      # Upload the report to TestArtifact directory
      - name: Output the result
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: TestArtifact

